---

- name: AWS Web Setup
  hosts: tag_Name_hostileadminweb
  user: "{{ clouduser }}"
  become: yes
  become_user: "{{ becomeuser }}"

  tasks:
    - name: Install AWS EPEL, nginx
      command: amazon-linux-extras install "{{ item }}" -y
      with_items:
        - epel
        - nginx1
      tags:
        - all
        - update

    - name: Install/update packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - nc
        - nmap
        - '*'
      tags:
        - all
        - update
      notify: Reboot

    - name: Create nginx log directory
      file:
        state: directory
        path: "/var/log/nginx/{{ domain }}"
      tags:
        - all
        - config

    - name: Copy nginx.conf
      copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      tags:
        - all
        - config

    - name: Template domain config
      template:
        src: templates/domain.conf.j2
        dest: /etc/nginx/conf.d/{{ domain }}.conf
        owner: root
        group: root
        mode: '0644'
      tags:
        - all
        - config

    - name: Setup filesystem for git repo
      file:
        state: absent
        path: "{{ docroot  }}"
      tags:
        - all
        - deployweb

    - name: Clone git repo
      git:
        repo: '{{ siterepo }}'
        dest: "{{ docroot }}"
        accept_hostkey: yes
        single_branch: yes
        version: master
      tags:
        - all
        - deployweb

    - name: Restart nginx
      command: echo "Notify nginx handler"
      notify: "restart nginx"
      tags:
        - all
        - deployweb
        - restartweb
        - config

  handlers:

    - name: Reboot
      reboot:

    - name: restart nginx
      service: name=nginx state=restarted
